### ISSUE TITLE
German language in english FAQ

### ISSUE THREAD

**Issue by SenseException** [spryker/spryker-academy#1]
While reading the FAQ of the new Spryker Academy, I found that the following questions are answered in german:

* How expensive is the average Spryker project?
* How might an MVP look like?

Those answers need to be in english. Are contributions done in HTML?

https://github.com/spryker/spryker-academy/blob/master/public/understanding_spryker/faq.html

**Comment by debbiedocs** [comment]
Hi Claudio Zizza,

Thank you for pointing this out. Yes contributions are done in html or in plain text in the comments area. 
We have removed the German text and you should be able to see the correct version in a few minutes.

Thanks,
The Academy Team

**Comment by SenseException** [comment]
Okay, seems like PRs are not welcome. Issues only it is. Thank you.

**Comment by debbiedocs** [comment]
PRs are welcome!

We manually migrate our content to source files for moderation and content reuse purposes. 

Thanks
