### ISSUE TITLE
Update references to PHP5

### ISSUE THREAD

**Issue by Sam-Burns** [spryker/spryker-academy#13]
Documentation refers to `php5-fpm`, for example, at https://github.com/spryker/spryker-academy/blob/4adb5a2df7f9940821146949801770e8612f4adb/public/getting_started/installation_guide.html#L288

But PHP5 isn't used on the VM anymore.

**Comment by dereuromark** [comment]
This should probably refer to php7.1-fpm if still needed.

**Comment by hhebbo** [comment]
Hi Sam, 
Thanks for pointing this out, we will update our documentation accordingly

**Comment by lenadoc** [comment]
This issue is fixed.
