### ISSUE TITLE
Information about PCI Compliance not correct 

### ISSUE THREAD

**Issue by felixgeyer** [spryker/spryker-academy#14]
In the [Payone module documentation](https://academy.spryker.com/developing_with_spryker/3rd-party_integration/payone/integration_payment_payone_credit_card.html) there is a paragraph about PCI Compliance. 
It says, there is no need for a certification if one uses the ajax-request method as creditcard information stays client side. This information seems wrong.

Even if you use a hosted iframe provided by the payment provider, you have to get a certain degree of compliance/conformity by answering 15 questions.

If the customer enters creditcard data in a self hosted form, you have to pass further security checks and fill out a form with 150 questions.   

Please validate these information and update the academy if necessary.

**Comment by lenadoc** [comment]
Hello Felix! Thanks for pointing this out. We will check this information.

**Comment by lenadoc** [comment]
Hi Felix! The documentation has been updated: https://academy.spryker.com/developing_with_spryker/industry_partner_integration/payone/v1_0/integration_payment_payone_credit_card.html. Thanks for your contribution.
