### ISSUE TITLE
Standardize the examples

### ISSUE THREAD

**Issue by petar-dambovaliev** [spryker/spryker-academy#16]
The introduction tutorial starts by going through creating a "HelloWorld" module with an index controller.
When you reach to the routing tutorual, you get a reference to a different controller with a different action that requires different params on the dependency provider.

I think, in the very first walkthough tutorial, things should be kept the same to avoid confusion.

**Comment by lenadoc** [comment]
Hi Petar,
Thanks for pointing this out. We will look into this and update the tutorial.
