### ISSUE TITLE
Wrong class used for DB config constants

### ISSUE THREAD

**Issue by PetarAtanasov** [spryker/spryker-academy#19]
https://academy.spryker.com/getting_started/configure_database_server.html

Change all the ApplicationConstants usages on that page to PropelConstants.
That's where the constants are defined.

**Comment by sveriger** [comment]
Yes, please.

And it's not config/Shared/config_default-development_DE.php
it's config/Shared/config_default-development.php in current demoshop.

**Comment by lenadoc** [comment]
Hello Petar and Sven,

Thank you very much for pointing out these issues. They have been fixed now.
Your further comments and suggestions would be greatly appreciated!

Regards,
The Academy Team
