### ISSUE TITLE
missing method in tables tutorial

### ISSUE THREAD

**Issue by petar-dambovaliev** [spryker/spryker-academy#20]
https://academy.spryker.com/enablement/tutorials_and_howtos/advanced_tutorials/t_working_tables.html?Highlight=table#Render    

Add this to the docs, the table doesn't work without the ajax action

```
/**
   * @return \Symfony\Component\HttpFoundation\JsonResponse
   */
    public function tableAction()
```

**Comment by lenadoc** [comment]
Hello Petar,
Thank you very much for your continued contribution to the Academy. 
Could you please elaborate a little bit on this issue: where specifically should the proposed code be added and why?
Thank you in advance!
