### ISSUE TITLE
Redescribe states definition

### ISSUE THREAD

**Issue by janmyszkier** [spryker/spryker-academy#27]
Please, redescribe:
```
States allow to describe in which state a sales order respectively the sales order item is in. 
```

Since this is not simple English (I'm actually not sure if this is correct English at all) please clarify the meaning of this. I believe this should be either:
```
States allow describing in which state each of the sales order items is in for a selected sales order.
```
or maybe
```
States allow describing in which state each order is in. States can also be used to define the same thing for each of the sales order item elements.
```

Whatever is now in the docs is not clear. Especially I cannot easily find any reference to sales order item state anywhere in the spryker XML files (not by file name, anyway).

**Comment by lenadoc** [comment]
Hello @janmyszkier,

We are very grateful for your continuous input! The sentence has been rephrased and the changes are already in the Academy.

Should you have any other comments and suggestions, don't hesitate to share them with us, we really appreciate it!

Regards,

The Academy Team
